# Site
title: "Gallantries Workshop"
description: >
  When Galaxy meets Carpentries to develop and deliver open training in life sciences
logo: 'assets/images/gallantries-logo-with-word-inverted-large.svg'
paginate: 12
email: 'fixme@example.com'
repository: fixme
gitter: fixme

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
  events:
    permalink: /event/:path/
    output: true